# Generated by Django 2.1.7 on 2019-03-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_featurechooce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureChooce',
            new_name='FeatureChoose',
        ),
    ]
