# Generated by Django 2.1.7 on 2019-03-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190331_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IssueInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineID', models.CharField(max_length=200)),
                ('Customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='issueinfo',
            name='Loacation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Location'),
        ),
        migrations.AddField(
            model_name='issueinfo',
            name='MachineModelName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Machine'),
        ),
    ]
