# Generated by Django 2.1.7 on 2019-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190331_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='CustomerName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='MachineName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
