# Generated by Django 2.1.7 on 2019-03-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190331_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='CustomerName',
            new_name='LocationName',
        ),
    ]
