# Generated by Django 2.1.7 on 2019-03-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190331_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerName',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='issueinfo',
            name='Customer',
        ),
        migrations.AddField(
            model_name='issueinfo',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.customer'),
        ),
    ]
