# Generated by Django 2.1.7 on 2019-03-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190331_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueinfo',
            name='MachineModelName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Machine'),
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='issueinfo',
            unique_together=set(),
        ),
    ]
