# Generated by Django 2.1.7 on 2019-03-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190331_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='Customer_Name',
        ),
        migrations.RemoveField(
            model_name='issueinfo',
            name='customer',
        ),
        migrations.AddField(
            model_name='issueinfo',
            name='Customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Customer'),
        ),
    ]
