# Generated by Django 2.1.7 on 2019-03-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190331_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueinfo',
            old_name='Loacation',
            new_name='Location',
        ),
    ]
