# Generated by Django 2.1.7 on 2019-03-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190331_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueinfo',
            old_name='mach_cust_id',
            new_name='Mach_Cust_ID',
        ),
    ]
