# Generated by Django 2.1.7 on 2019-03-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20190331_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueinfo',
            name='IssueDescribe',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='issueinfo',
            name='IssueTopic',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='issueinfo',
            name='MachineJamStatus',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
